const marketingProjects = [
  {
    id: 2,
    title: "AirLine Reservation Window",
    slug: "airLine-reservation-window",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761826394/blog-app/blogs/blogs/1761826391167-airlinereservationwindow.com.jpg",
    subImage: "/assist/portfolio/marketing/airline.png",
    description:
      "AirlineReservationWindow is a digital marketing and UX initiative aimed at creating a strong presence in a competitive flight booking market.",
    url: " ",
    buttonText: " ",
    points: [
      "Infogentech implemented SEO, content marketing, and UX enhancements to improve visibility and conversions.",
      "Took data insights from Google Search Console to guide performance-driven optimizations.",
      "Achieved steady organic growth and improved brand recognition through transparency and support.",
    ],
    date: "January - Continuing (2025) ",
    duration: "9 months",
    tools: [
      "Google Search Console",
      "Google Analytics ",
      "WordPress / CMS ",
      "SEMRush / Ahrefs ",
      "Canva",
    ],
    client: "AirlineReservationWindow.com – Online Flight Booking Platform",
    location: "Global (Online Service)",
    modules: [
      "   SEO (On-Page & Off-Page) ",
      "Content Marketing (Travel Guides, Blogs, Deals) ",
      "UX & Website Optimization ",
      "Customer Support (24/7 Chat & Phone) ",
      "Performance Tracking (Google Search Console) ",
      "Conversion Rate Optimization (Future Focus) ",
    ],
    expertise: [
      "    Search Engine Optimization ",
      "Content Strategy & Marketing ",
      "User Experience Design ",
      "Brand Positioning & Trust Building ",
      "Customer Retention & Engagement ",
      "Conversion Optimization",
    ],
  },
  {
    id: 3,
    title: "@ananyakhurana_30 – Fashion Influencer ",
    slug: "ananyakhurana30-Fashion-Influencer",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761828799/blog-app/blogs/blogs/1761828795431-ananya_khurana_digital_growth_2.jpg",
    subImage: "/assist/portfolio/marketing/ananya.png",
    description:
      "A focused social media growth campaign for fashion influencer @ananyakhurana_30 is designed to convert a personal style into a strong brand presence.",
    points: [
      "Infogentech creates a clear content structure using reels, trends, posting schedules, and discoverable brand presence.",
      "Profile optimization for brand collaborations using consistent visuals, CTAs, and storytelling.",
      "Without paid promotions, Infogentech delivered higher reach, strong engagement, and increased brand interest.",
    ],
    date: "January - Continuing (2025) ",
    duration: "2 months",
    tools: [
      " Instagram Analytics ",
      "Meta Business Suite ",
      "Canva (Visual Design & Reels Assets) ",
      "Notion (Content Calendar) ",
      "Hashtag Research Tools ",
    ],
    client: "@ananyakhurana_30 – Fashion Influencer ",
    location: "India (Instagram Platform)",
    modules: [
      "Profile Optimization",
      "Content Strategy & Calendar (Fashion Tips, GRWMs, Trends) ",
      "Audience Engagement (Polls, Q&As, Replies) ",
      "Reels Strategy (Trending Sounds, Fashion Aesthetics) ",
      "Brand Collaboration Positioning ",
      "Hashtag Research & Implementation ",
    ],
    expertise: [
      "Social Media Growth Strategy ",
      "Content Planning & Execution ",
      "Influencer Branding & Positioning ",
      "Engagement Tactics ",
      "Performance Tracking & Optimization ",
      "Brand Partnership Readiness ",
    ],
      url: " ",
    buttonText: " ",
  },
  {
    id: 4,
    title: "Bluestar Buildprop – Real Estate Brand ",
    slug: "Bluestar-Buildprop-Real-Estate-Brand",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761828932/blog-app/blogs/blogs/1761828929420-bluestar_buildrpod_digital_growth_1.jpg",
    subImage: "/assist/portfolio/marketing/TechHiveExpanding.png",
    description:
      "A targeted Instagram strategy for a real estate brand, Bluestar Buildprop crafted to convert social visibility into buyer interest.",
    points: [
      "To showcase luxury projects and expertise, Infogentech creates a consistent branding, optimized profile, and structured content.",
      "Implemented data-driven content, stories, and engagement tactics to make clients and buyers understand better.",
      "Achieved measurable growth within one month. This includes a higher reach, increased profile clicks, and new collaboration opportunities.",
    ],
    date: "July – August 2025 ",
    duration: "1 month",
    tools: [
      "    Instagram Analytics ",
      "Meta Business Suite ",
      "Canva (Content & Reels Design) ",
      "Notion (Content Calendar) ",
      "Hashtag Research Tools ",
    ],
    client: "Bluestar Buildprop – Real Estate Brand ",
    location: "India (Instagram Platform) ",
    modules: [
      "Profile Optimization (Bio, Highlights, Location Tags) ",
      "Content Strategy (Property Reels, Tips, Neighborhood Features, Success Stories) ",
      "Engagement Strategy (Replies, DMs, Daily Interaction) ",
      "Story Marketing (Property Updates, Site Visits) ",
      "Hashtag Research & Collaborations ",
      "Performance Tracking & Optimization ",
    ],
    expertise: [
      "    Social Media Growth Strategy ",
      "Content Branding & Visual Identity ",
      "Real Estate Digital Marketing ",
      "Community Engagement ",
      "Influencer/Partner Collaborations ",
      "Data-Driven Optimization ",
    ],
      url: " ",
    buttonText: " ",
  },
  {
    id: 5,
    title:
      "Soho Resort Corbett — Luxury Nature Resort in Jim Corbett, Uttarakhand ",
    slug: "Soho-Resort-Corbett-Luxury-Nature-Resort-in-Jim-Corbett-Uttarakhand",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761826525/blog-app/blogs/blogs/1761826521641-case_study__soho_corbett_resort.jpg",
    subImage: "/assist/portfolio/marketing/soho.png",
    description:
      "Infogentech ran a digital marketing campaign to increase room sales and destination wedding bookings for Soho Resort Corbett.",
    points: [
      "Leveraged Google Ads, Meta Ads, precise targeting, and seasonal creatives to capture high-intent audiences.",
      "Generated over 11,000 qualified leads and ₹1.90 Cr in business within eight months.",
      "Secured a 13.4x ROI, establishing the resort as a premium wedding and hospitality destination.",
    ],
    date: "November 2024 – June 2025 ",
    duration: "8 Months ",
    tools: [
      "   Meta Ads Manager ",
      "Google Ads (Search, Display, Performance Max) ",
      "Google Analytics + Tag Manager ",
      "Canva / Premiere Pro (Ad Creatives) ",
      "Landing Page Builders (Webflow/WordPress)",
    ],
    client:
      "Soho Resort Corbett — Luxury Nature Resort in Jim Corbett, Uttarakhand ",
    location: "Global (Online Service)",
    modules: [
      "   Meta Ads (Facebook + Instagram) ",
      "Google Ads (Search, Display, Performance Max) ",
      "Landing Page Optimization ",
      "Conversion Tracking Setup (Meta Pixel + Google) ",
      "Creative Strategy (Videos, Carousels, Testimonials) ",
      "Retargeting & Audience Segmentation",
    ],
    expertise: [
      "    Performance Marketing (Meta & Google Ads) ",
      "Direct Booking Growth Strategy ",
      "Hospitality Digital Marketing ",
      "High-Intent Keyword Targeting ",
      "Ad Budget Scaling & ROI Optimization ",
    ],
      url: " ",
    buttonText: " ",
  },
  {
    id: 6,
    title:
      "SeaC Overseas Education Consultants — Study Abroad Consultancy (US Programs) ",
    slug: "SeaC-Overseas-Education-Consultants-Study-Abroad-Consultancy-US-Programs",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761827026/blog-app/blogs/blogs/1761827022192-somo_education_abroad_consultants_case_study.png",
    subImage: "/assist/portfolio/marketing/SomoEducation.png",
    description:
      "Infogentech performed a performance-driven digital marketing campaign. We focused on increasing student leads and US Master’s admissions.",
    points: [
      "Ran targeted Meta ad campaigns for students and B2B education partners with clear value-led messaging.",
      "Generated over 2,000 qualified student leads and 100 confirmed admission files.",
      "Achieved an estimated ₹2 Cr in revenue with a strong 24x return on ad spend.",
    ],
    date: "November 2024 – June 2025 ",
    duration: "4 Months ",
    tools: [
      "   Meta Ads Manager ",
      "Facebook Instant Forms ",
      "Canva / Figma (Ad Creatives) ",
      "Google Sheets (ROI Calculation & Lead Tracking)",
    ],
    client:
      "SeaC Overseas Education Consultants — Study Abroad Consultancy (US Programs) ",
    location: "India (Meta Ads Campaigns)",
    modules: [
      "  Lead Generation (Meta Ads Instant Forms) ",
      "Fee Structure Marketing (Transparent ROI-driven creatives) ",
      "B2B Outreach Campaigns (Immigration & Education Consultants) ",
      "Retargeting (Engaged Audience Nurturing) ",
      "Performance Tracking & ROI Analysis ",
    ],
    expertise: [
      "    Performance Marketing (Meta Ads) ",
      "Lead Generation Campaigns ",
      "Education Industry Digital Marketing ",
      "B2B & B2C Audience Segmentation ",
      "Revenue Modeling & ROI Optimization",
    ],
      url: " ",
    buttonText: " ",
  },
  {
    id: 7,
    title: "Suii_Thaga — Fashion Brand on Instagram ",
    slug: "Suii_Thaga-Fashion-Brand-on-Instagram",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761829200/blog-app/blogs/blogs/1761829196040-suii_thaga_digital_growth_1.jpg",
    subImage: "/assist/portfolio/marketing/Suii_thaga.png",
    description:
      "For a fashion Instagram brand, Suii_Thaga, Infogentech drove a structured growth by turning content into engagement and sales through a clear social media strategy.",
    points: [
      "Created audience-focused reels, posts, and stories to improve reach and discoverability.",
      "Strengthened the brand’s look and messaging with cohesive visuals, captions, and hashtags.",
      "Increased follower growth, engagement (story replies), profile visits, and website traffic via active interaction and promotions.",
    ],
    date: "April – May 2025",
    duration: "1 Month",
    tools: [
      "   Instagram Analytics ",
      "Meta Ads Manager ",
      "Canva / Figma (Design Templates) ",
    ],
    client: "Suii_Thaga — Fashion Brand on Instagram ",
    location: "United States (Instagram-first brand)",
    modules: [
      " Content Calendar Planning ",
      "Reels & Story Optimization ",
      "Community Engagement ",
      "Instagram Ads Boosting ",
      "Hashtag & Caption Strategy ",
    ],
    expertise: [
      "   Instagram Growth Strategy ",
      "Content Marketing ",
      "Visual Identity Design ",
      "Performance Tracking ",
    ],
      url: " ",
    buttonText: " ",
  },
  {
    id: 8,
    title: "ExamStudyZone.com — Educational Platform ",
    slug: "ExamStudyZone.com-Educational-Platform",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761826656/blog-app/blogs/blogs/1761826651962-exam_study_zone_case_study.jpg",
    subImage: "/assist/portfolio/marketing/examStudy.png",
    description:
      "Infogentech significantly boosted ExamStudyZone's visibility, engagement, and organic reach with a strategic SEO and content-led growth approach.",
    points: [
      "Optimized search visibility by researching long-tail, exam-focused keywords and adjusting on-page elements.",
      "Improved site speed, mobile usability, and internal linking; created SEO-friendly resources.",
      "Doubled clicks/impressions (over 200% growth), improved CTR, and strengthened keyword rankings on Google and Bing.",
    ],
    date: "November 2024 – June 2025 ",
    duration: "8 Months ",
    tools: [
      "   Google Search Console ",
      "Bing Webmaster Tools ",
      "SEMrush ",
      "Ubersuggest ",
    ],
    client: "ExamStudyZone.com — Educational Platform",
    location: "Global (Online/E-learning Platform) ",
    modules: [
      "    SEO Optimization ",
      "Content Expansion ",
      "Technical Improvements ",
      "Monitoring & Analysis ",
    ],
    expertise: [
      "   Search Engine Optimization (SEO) ",
      "Content Strategy & Writing ",
      "Technical SEO & Site Optimization ",
      "Education Marketing ",
      "Keyword Research & Analytics ",
    ],
      url: " ",
    buttonText: " ",
  },
  {
    id: 9,
    title: "iClinix — Specialized Eye Care Hospital ",
    slug: "iClinix-Specialized-Eye-Care-Hospital",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761826882/blog-app/blogs/blogs/1761826877216-iclini_x_case_study.jpg",
    subImage: "/assist/portfolio/marketing/IClini.png",
    description:
      "Infogentech boosted patient inquiries and visibility for iClinix eye care hospital using a mix of Google Ads for immediate growth and SEO for long-term results.",
    points: [
      "Optimized high-intent search campaigns, driving consistent patient inquiries for eye treatments.",
      "Improved organic reach and credibility through keyword research, on-page SEO, and local optimization.",
      "Patient-focused messaging and expert-led campaigns boosted CTR, cut CPC, and built brand trust.",
    ],
    date: "May 2025",
    duration: "1 Month ",
    tools: [
      "    Google Ads ",
      "Google Search Console ",
      "SEMrush ",
      "Local SEO Listings",
    ],
    client: "iClinix — Specialized Eye Care Hospital",
    location: "Delhi NCR, India ",
    modules: [
      " Google Ads Campaigns ",
      "SEO Optimization ",
      "Lead Generation ",
      "Content Strategy",
    ],
    expertise: [
      "  Search Engine Optimization (SEO) ",
      "Google Ads & PPC Campaigns ",
      "Local SEO & Patient Targeting ",
      "Healthcare Marketing ",
      "Content Optimization ",
    ],
      url: " ",
    buttonText: " ",
  },
];

export default marketingProjects;
