const developmentProjects = [
  {
    id: 1,
    title: "LaraClean service",
    slug: "laraClean-service",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758866786/blog-app/categories/hukwgvw3xqgqcau0nyr7.jpg",
    subImage: "/assist/portfolio/development/dryCleaning.webp",
    description:
      "Laraclean is a Delhi based company specializing in professional dry-cleaning services, with the focus to offer clean and neat cleaning services. The brand focuses on the integration of modern technology in cleaning and personal customer service. The mission is to simplify garment care for every customer by keeping clothes fresh and long lasting.",
    points: [
      "Wireframes, Prototypes, and High-fidelity design were created to be understandable and easy to use.",
      "Customization of WordPress using Elementor, styling of the theme, and integration of plugins.",
      "The use of custom typography, colors, and visual hierarchy ensures the brand identity is consistent.",
    ],
    date: "June 2025 ",
    duration: "4 months ",
    tools: [
      "Elementor",
      "WordPress",
      "Figma",
      "Adobe Illustrator ",
      "Adobe Photoshop",
    ],
    client: "LaraClean – Professional Dry-Cleaning Service ",
    location: "Delhi, India ",
    modules: [
      "Research",
      "Wireframing",
      "Prototyping",
      "WordPress Development",
      "Testing & Optimization ",
    ],
    expertise: [
      "UI/UX Design",
      "User Research ",
      "Wireframing & Prototyping",
      "Web Design",
      "Interaction Design",
      "WordPress Development",
      "Responsive Design ",
      "Performance Optimization ",
    ],
  },
  {
    id: 2,
    title: "ShaadiKarwaDu – Wedding Planning & Coordination",
    slug: "shaadiKarwadu-wedding-planning",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758872051/blog-app/categories/lkvacf2yfdjsq5nwxjob.jpg",
    subImage: "/assist/portfolio/development/ShaadiKarwadu.png",
    description:
      "ShaadiKarwaDu is a total wedding solutions brand, which aims to make each event memorable and stress-free. It is a combination of creativity, tradition, modern elegance, personalized arrangements and planning. The mission of the brand is to make dream weddings come true and do it with perfect implementation and emotional moments.",
    points: [],
    date: "May 2025 ",
    duration: "8 weeks ",
    tools: [
      "     Figma ",
      "Canva ",
      "Trello / Asana ",
      "Slack ",
      "Google Workspace ",
    ],
    client: "ShaadiKarwaDu – Wedding Planning & Coordination",
    location: "India (Nationwide Services)",
    modules: [
      " Venue Management ",
      "Vendor Coordination ",
      "Event Décor & Styling ",
      "Logistics & Operations ",
      "Guest Experience ",
      "Photography & Media ",
    ],
    expertise: [
      "Event Planning & Coordination ",
      "Luxury & Destination Weddings ",
      "Brand & Experience Design ",
      "Vendor Management ",
      "Logistics Planning ",
      "Content & Storytelling",
    ],
  },
  // {
  //   id: 3,
  //   title: "Madirakshi app",
  //   slug: "madirakshi-app",
  //   image: "/assist/portfolio/development/MadirakshiStudycase.png",
  //   subImage: "/assist/portfolio/development/madrirakshi.png",
  //   description:
  //     "Madirakshi, an emerging digital platform, became our marketing partner to improve their app onboarding experience. We redefined the onboarding flow to retain and satisfy our customers while ensuring that they adopt the features. Figma and WordPress aided in creating a fluid, useful process and a higher level of engagement while bringing long engagement periods and customer success with it.",
  //   points: [],
  //   date: "June 2025 ",
  //   duration: "4 months ",
  //   tools: [
  //     "Elementor",
  //     "WordPress",
  //     "Figma",
  //     "Adobe Illustrator ",
  //     "Adobe Photoshop",
  //   ],
  //   client: "LaraClean – Professional Dry-Cleaning Service ",
  //   location: "Delhi, India ",
  //   modules: [
  //     "Research",
  //     "Wireframing",
  //     "Prototyping",
  //     "WordPress Development",
  //     "Testing & Optimization ",
  //   ],
  //   expertise: [
  //     "UI/UX Design",
  //     "User Research ",
  //     "Wireframing & Prototyping",
  //     "Web Design",
  //     "Interaction Design",
  //     "WordPress Development",
  //     "Responsive Design ",
  //     "Performance Optimization ",
  //   ],
  // },
  {
    id: 4,
    title: "Avarta Jewellery",
    slug: "Avarta-jewellery",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758868867/blog-app/categories/rgm9p4wvvhejttch94gi.jpg",
    subImage: "/assist/portfolio/development/avartajewellery.png",
    description:
      "Avarta Jewellery celebrates the timeless beauty of ancient artistry while embracing the sophistication of modern design. Each piece is crafted carefully with precision, beauty and a classy look. Avarta transforms jewellery into more than just adornment, it becomes a symbol of beauty, identity and cherished memories.",
    points: [],
    date: "May – July 2025",
    duration: "6 weeks ",
    tools: [
      "Figma",
      "Miro",
      "Google Forms (Survey) ",
      "Zoom (Interviews) ",
      "Illustrator",
      "Photoshop",
    ],
    client: "Avarta Jewellery – Premium Jewellery Brand",
    location: "Mumbai, India",
    modules: [
      "Research & Empathize ",
      "Define",
      "Ideate",
      "Design & Prototype",
      "User Testing",
      "Information Architecture",
      "Competitor Analysis",
    ],
    expertise: [
      "UI/UX Design",
      "User Research & Personas",
      "Empathy Mapping",
      "Wireframing & Prototyping",
      "Visual Design (Typography, Colors, Grids)",
      "E-commerce Experience Design",
      "Trust & Transparency Integration ",
      "Responsive Web Design",
    ],
  },
  {
    id: 5,
    title: "Soouqna’s E-Commerce Platform",
    slug: "soouqna-Commerce-Platform",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758796090/blog-app/categories/hlxlfw0cuqlvhhe0cutg.jpg",
    subImage: "/assist/portfolio/development/sooquna.png",
    description:
      "Soouqna is a fast-selling e-commerce platform, which aims at improving its logistics, order handling and speed of delivery by contracting Zebra to integrate with the API. The integration facilitates barcode scanning, enhances the performance of the printer and increases the overall operating accuracy, making the shopping experience of customers smooth in all regions.",
    points: [
      "Secure Login: Added OTP & email/password authentication.",
      "Smart Search: Enabled location, QR & image-based product discovery.",
      "Faster Performance: Optimized backend for speed & stability.",
    ],

    date: "March 2025",
    duration: "4 weeks ",
    tools: ["Zebra API ", "Node.js", "React", "MongoDB"],
    client: "Soouqna – E-commerce Platform",
    location: "Iraq",
    modules: [
      "Secure Login API",
      "Location API ",
      "QR Code API",
      "Image Search API",
      "Performance Optimization ",
      "Deployment & Fixes",
    ],
    expertise: [
      " API Integration",
      "E-commerce Development",
      "Performance Optimization",
      "User Authentication",
      "Search & Discovery (QR / Image)",
      "Logistics & Delivery Tech",
    ],
  },
];

export default developmentProjects;
