const developmentProjects = [
  {
    id: 1,
    title: "LaraClean service",
    slug: "laraClean-service",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761894913/blog-app/blogs/blogs/1761894907787-lara_clean_casestudy_2.jpg",
    subImage: "/assist/portfolio/development/dryCleaning.webp",
    description:
      "This project highlights the design process of developing a clean, functional, and engaging website for LaraClean. It was designed to offer an easy booking experience to users and demonstrate the professionalism and trust of the brand. ",
    url: "https://laraclean.com/",
    buttonText: "Visit Website",
    points: [
      "Wireframes, Prototypes, and High-fidelity design were created to be understandable and easy to use.",
      "Customization of WordPress using Elementor, styling of the theme, and integration of plugins.",
      "The use of custom typography, colors, and visual hierarchy ensures the brand identity is consistent.",
    ],
    date: "June 2025 ",
    duration: "4 months ",
    tools: [
      "Elementor",
      "WordPress",
      "Figma",
      "Adobe Illustrator ",
      "Adobe Photoshop",
    ],
    client: "LaraClean – Professional Dry-Cleaning Service ",
    location: "Delhi, India ",
    modules: [
      "Research",
      "Wireframing",
      "Prototyping",
      "WordPress Development",
      "Testing & Optimization ",
    ],
    expertise: [
      "UI/UX Design",
      "User Research ",
      "Wireframing & Prototyping",
      "Web Design",
      "Interaction Design",
      "WordPress Development",
      "Responsive Design ",
      "Performance Optimization ",
    ],
  },
  {
    id: 2,
    title: "ShaadiKarwaDu – Wedding Planning & Coordination",
    slug: "shaadiKarwadu-wedding-planning",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761992949/blog-app/blogs/blogs/1761992942007-shaadi-karwadu-landing-page-(3)-min.jpg",
    subImage: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761551557/blog-app/blogs/blogs/1761551548973-shaddikarvado.jpg",
    description:
      "Madirakshi, an emerging digital platform, became our marketing partner to improve their app onboarding experience. We redefined the onboarding flow to retain and satisfy our customers while ensuring that they adopt the features. Figma and WordPress aided in creating a fluid, useful process and a higher level of engagement while bringing long engagement periods and customer success with it.",
    points: [],
    date: "May 2025 ",
    duration: "8 weeks ",
    tools: [
      "     Figma ",
      "Canva ",
      "Trello / Asana ",
      "Slack ",
      "Google Workspace ",
    ],
    client: "ShaadiKarwaDu – Wedding Planning & Coordination",
    location: "India (Nationwide Services)",
    modules: [
      " Venue Management ",
      "Vendor Coordination ",
      "Event Décor & Styling ",
      "Logistics & Operations ",
      "Guest Experience ",
      "Photography & Media ",
    ],
    expertise: [
      "Event Planning & Coordination ",
      "Luxury & Destination Weddings ",
      "Brand & Experience Design ",
      "Vendor Management ",
      "Logistics Planning ",
      "Content & Storytelling",
    ],
     url: " ",
    buttonText: " ",
  },
  // {
  //   id: 3,
  //   title: "Madirakshi app",
  //   slug: "madirakshi-app",
  //   image: "/assist/portfolio/development/MadirakshiStudycase.png",
  //   subImage: "/assist/portfolio/development/madrirakshi.png",
  //   description:
  //     "Madirakshi, an emerging digital platform, became our marketing partner to improve their app onboarding experience. We redefined the onboarding flow to retain and satisfy our customers while ensuring that they adopt the features. Figma and WordPress aided in creating a fluid, useful process and a higher level of engagement while bringing long engagement periods and customer success with it.",
  //   points: [],
  //   date: "June 2025 ",
  //   duration: "4 months ",
  //   tools: [
  //     "Elementor",
  //     "WordPress",
  //     "Figma",
  //     "Adobe Illustrator ",
  //     "Adobe Photoshop",
  //   ],
  //   client: "LaraClean – Professional Dry-Cleaning Service ",
  //   location: "Delhi, India ",
  //   modules: [
  //     "Research",
  //     "Wireframing",
  //     "Prototyping",
  //     "WordPress Development",
  //     "Testing & Optimization ",
  //   ],
  //   expertise: [
  //     "UI/UX Design",
  //     "User Research ",
  //     "Wireframing & Prototyping",
  //     "Web Design",
  //     "Interaction Design",
  //     "WordPress Development",
  //     "Responsive Design ",
  //     "Performance Optimization ",
  //   ],
  // },
  {
    id: 4,
    title: "Avarta Jewellery",
    slug: "Avarta-jewellery",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761287094/lpb53tidbisvfzjal0ew.png",
    subImage: "/assist/portfolio/development/avartajewellery.png",
    description:
      "Avarta Jewellery is a luxury brand that has a reputation for classic beauty and contemporary workmanship. They collaborated with us to design and develop a rich site. We provided the construction of category-based collections, blogs, customer resource, and e-commerce functionality, which would be smooth and user-friendly, so that the experience provided would be interesting to the jewellery lovers of today.",
    points: [],
    date: "May – July 2025",
    duration: "6 weeks ",
    tools: [
      "Figma",
      "Miro",
      "Google Forms (Survey) ",
      "Zoom (Interviews) ",
      "Illustrator",
      "Photoshop",
    ],
    client: "Avarta Jewellery – Premium Jewellery Brand",
    location: "Mumbai, India",
    modules: [
      "Research & Empathize ",
      "Define",
      "Ideate",
      "Design & Prototype",
      "User Testing",
      "Information Architecture",
      "Competitor Analysis",
    ],
    expertise: [
      "UI/UX Design",
      "User Research & Personas",
      "Empathy Mapping",
      "Wireframing & Prototyping",
      "Visual Design (Typography, Colors, Grids)",
      "E-commerce Experience Design",
      "Trust & Transparency Integration ",
      "Responsive Web Design",
    ],
      url: "https://www.avartajewellery.com/ ",
    buttonText: "Visit Website",
  },
  {
    id: 5,
    title: "Soouqna’s E-Commerce Platform",
    slug: "soouqna-Commerce-Platform",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1761827846/blog-app/blogs/blogs/1761827842965-soouqna_casestudy.jpg",
    subImage: "/assist/portfolio/development/sooquna.png",
    description:
      "Soouqna, a growing e-commerce platform, partnered with Zebra to enhance logistics and delivery. API connectivity enabled seamless barcode scanning, better printer efficiency, and improved operational accuracy for faster, more reliable customer service.",
    points: [
      "Secure Login: Added OTP & email/password authentication.",
      "Smart Search: Enabled location, QR & image-based product discovery.",
      "Faster Performance: Optimized backend for speed & stability.",
    ],

    date: "March 2025",
    duration: "4 weeks ",
    tools: ["Zebra API ", "Node.js", "React", "MongoDB"],
    client: "Soouqna – E-commerce Platform",
    location: "Iraq",
    modules: [
      "Secure Login API",
      "Location API ",
      "QR Code API",
      "Image Search API",
      "Performance Optimization ",
      "Deployment & Fixes",
    ],
    expertise: [
      " API Integration",
      "E-commerce Development",
      "Performance Optimization",
      "User Authentication",
      "Search & Discovery (QR / Image)",
      "Logistics & Delivery Tech",
    ],
     url: "https://vercel.com/infos-projects-e2fe1ec1",
    buttonText: "Visit Website",
  },
];

export default developmentProjects;
