const marketingProjects = [
  {
    id: 2,
    title: "AirLine Reservation Window",
    slug: "airLine-reservation-window",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758796018/blog-app/categories/ax4e554vqfopvqee4qrw.jpg",
    subImage: "/assist/portfolio/marketing/airline.png",
    description:
      "Airline Reservation Window is a smart booking program that aims at streamlining the process of planning air travel. It has an easy-to-use interface that helps customers to search, compare and book flights easily. It is a convenient service that enables a smooth travel booking experience to both individuals and businesses.",
    points: [
      "Content Strategy: Developed keyword clusters around sustainable living.",
      "Blog Campaigns: Created eco-lifestyle guides and product highlights.",
      "Conversion Optimization: Enhanced product pages with persuasive copy.",
    ],
    date: "January - Continuing (2025) ",
    duration: "9 months",
    tools: [
      "Google Search Console",
      "Google Analytics ",
      "WordPress / CMS ",
      "SEMRush / Ahrefs ",
      "Canva",
    ],
    client: "AirlineReservationWindow.com – Online Flight Booking Platform",
    location: "Global (Online Service)",
    modules: [
      "   SEO (On-Page & Off-Page) ",
      "Content Marketing (Travel Guides, Blogs, Deals) ",
      "UX & Website Optimization ",
      "Customer Support (24/7 Chat & Phone) ",
      "Performance Tracking (Google Search Console) ",
      "Conversion Rate Optimization (Future Focus) ",
    ],
    expertise: [
      "    Search Engine Optimization ",
      "Content Strategy & Marketing ",
      "User Experience Design ",
      "Brand Positioning & Trust Building ",
      "Customer Retention & Engagement ",
      "Conversion Optimization",
    ],
  },
  {
    id: 3,
    title: "@ananyakhurana_30 – Fashion Influencer ",
    slug: "ananyakhurana30-Fashion-Influencer",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758869279/blog-app/categories/lhde7umyzqnxnydsfinb.jpg",
    subImage: "/assist/portfolio/marketing/ananya.png",
    description:
      "@ananyakhurana_30 is the creative voice that is focused in the digital sphere and is enthusiastic about the field of lifestyle, fashion and modern storytelling. Being a fashion follower with a sharp eye and attraction towards interesting and captivating content, the profile encourages followers by providing interesting content, sincere work and relatable stories to create a lively community that values individuality, creativity and everyday experiences in style.",
    points: [
      "SEO Articles: Researched and wrote fitness tips & nutrition advice.",
      "Community Content: Engaging social posts and challenges.",
      "App Store Optimization: Optimized descriptions for downloads.",
    ],
    date: "January - Continuing (2025) ",
    duration: "2 months",
    tools: [
      " Instagram Analytics ",
      "Meta Business Suite ",
      "Canva (Visual Design & Reels Assets) ",
      "Notion (Content Calendar) ",
      "Hashtag Research Tools ",
    ],
    client: "@ananyakhurana_30 – Fashion Influencer ",
    location: "India (Instagram Platform)",
    modules: [
      "Profile Optimization",
      "Content Strategy & Calendar (Fashion Tips, GRWMs, Trends) ",
      "Audience Engagement (Polls, Q&As, Replies) ",
      "Reels Strategy (Trending Sounds, Fashion Aesthetics) ",
      "Brand Collaboration Positioning ",
      "Hashtag Research & Implementation ",
    ],
    expertise: [
      "Social Media Growth Strategy ",
      "Content Planning & Execution ",
      "Influencer Branding & Positioning ",
      "Engagement Tactics ",
      "Performance Tracking & Optimization ",
      "Brand Partnership Readiness ",
    ],
  },
  {
    id: 4,
    title: "Bluestar Buildprop – Real Estate Brand ",
    slug: "Bluestar-Buildprop-Real-Estate-Brand",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758869387/blog-app/categories/hfa4k7vqodzja5sgeuat.jpg",
    subImage: "/assist/portfolio/marketing/TechHiveExpanding.png",
    description:
      "Bluestar Builprop is a progressive real estate and property development firm dedicated to developing modern, sustainable and value oriented spaces. Bluestar Builprop, with its emphasis on quality, innovation and customer trust, provides residential and commercial projects, redefining the standards of living, not to mention long-term growth and fulfilling its customers and communities.",
    points: [
      "Whitepapers: Produced in-depth industry resources.",
      "Case Studies: Showcased client success stories.",
      "LinkedIn Marketing: Published expert insights & updates.",
    ],
    date: "July – August 2025 ",
    duration: "1 month",
    tools: [
      "    Instagram Analytics ",
      "Meta Business Suite ",
      "Canva (Content & Reels Design) ",
      "Notion (Content Calendar) ",
      "Hashtag Research Tools ",
    ],
    client: "Bluestar Buildprop – Real Estate Brand ",
    location: "India (Instagram Platform) ",
    modules: [
      "Profile Optimization (Bio, Highlights, Location Tags) ",
      "Content Strategy (Property Reels, Tips, Neighborhood Features, Success Stories) ",
      "Engagement Strategy (Replies, DMs, Daily Interaction) ",
      "Story Marketing (Property Updates, Site Visits) ",
      "Hashtag Research & Collaborations ",
      "Performance Tracking & Optimization ",
    ],
    expertise: [
      "    Social Media Growth Strategy ",
      "Content Branding & Visual Identity ",
      "Real Estate Digital Marketing ",
      "Community Engagement ",
      "Influencer/Partner Collaborations ",
      "Data-Driven Optimization ",
    ],
  },
  {
    id: 5,
    title:
      "Soho Resort Corbett — Luxury Nature Resort in Jim Corbett, Uttarakhand ",
    slug: "Soho-Resort-Corbett-Luxury-Nature-Resort-in-Jim-Corbett-Uttarakhand",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758791929/blog-app/categories/obtbx84xw8gmqn0ooom3.jpg",
    subImage: "/assist/portfolio/marketing/soho.png",
    description:
      "Soho Corbett is a nature resort that is luxurious and located in the Jim Corbett National Park, Uttarakhand. It is known to be famous in terms of its tranquil location and Kumaon style of hospitality services to its visitors. Its exceptional combination of comfort, style and wilderness has made it a name to reckon with in the hotel business.",
    points: [
      "Lookbooks: Created interactive seasonal fashion guides.",
      "Influencer Content: Managed blog and collab posts.",
      "SEO Optimization: Trend-driven keyword strategies.",
    ],
    date: "November 2024 – June 2025 ",
    duration: "8 Months ",
    tools: [
      "   Meta Ads Manager ",
      "Google Ads (Search, Display, Performance Max) ",
      "Google Analytics + Tag Manager ",
      "Canva / Premiere Pro (Ad Creatives) ",
      "Landing Page Builders (Webflow/WordPress)",
    ],
    client:
      "Soho Resort Corbett — Luxury Nature Resort in Jim Corbett, Uttarakhand ",
    location: "Global (Online Service)",
    modules: [
      "   Meta Ads (Facebook + Instagram) ",
      "Google Ads (Search, Display, Performance Max) ",
      "Landing Page Optimization ",
      "Conversion Tracking Setup (Meta Pixel + Google) ",
      "Creative Strategy (Videos, Carousels, Testimonials) ",
      "Retargeting & Audience Segmentation",
    ],
    expertise: [
      "    Performance Marketing (Meta & Google Ads) ",
      "Direct Booking Growth Strategy ",
      "Hospitality Digital Marketing ",
      "High-Intent Keyword Targeting ",
      "Ad Budget Scaling & ROI Optimization ",
    ],
  },
  {
    id: 6,
    title:
      "SeaC Overseas Education Consultants — Study Abroad Consultancy (US Programs) ",
    slug: "SeaC-Overseas-Education-Consultants-Study-Abroad-Consultancy-US-Programs",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758791858/blog-app/categories/e8qyhrdupkjhhhuc7nv4.png",
    subImage: "/assist/portfolio/marketing/SomoEducation.png",
    description:
      "SeaC Overseas, a top education consultancy firm in the US, wanted to increase the number of student admissions and stay on top using online marketing. Using Meta campaigns that focus on students and B2B partners, they focused on open fee models, career development and job opportunities. The ad planning strategies produce quality leads, good partnerships and high revenue increase in their master programs.",
    points: [
      "Health Blogs: Easy-to-read guides on conditions and treatments.",
      "SEO Pages: Focused on high-volume health queries.",
      "Trust Signals: Developed authoritative medical resources.",
    ],
    date: "November 2024 – June 2025 ",
    duration: "4 Months ",
    tools: [
      "   Meta Ads Manager ",
      "Facebook Instant Forms ",
      "Canva / Figma (Ad Creatives) ",
      "Google Sheets (ROI Calculation & Lead Tracking)",
    ],
    client:
      "SeaC Overseas Education Consultants — Study Abroad Consultancy (US Programs) ",
    location: "India (Meta Ads Campaigns)",
    modules: [
      "  Lead Generation (Meta Ads Instant Forms) ",
      "Fee Structure Marketing (Transparent ROI-driven creatives) ",
      "B2B Outreach Campaigns (Immigration & Education Consultants) ",
      "Retargeting (Engaged Audience Nurturing) ",
      "Performance Tracking & ROI Analysis ",
    ],
    expertise: [
      "    Performance Marketing (Meta Ads) ",
      "Lead Generation Campaigns ",
      "Education Industry Digital Marketing ",
      "B2B & B2C Audience Segmentation ",
      "Revenue Modeling & ROI Optimization",
    ],
  },
  {
    id: 7,
    title: "Suii_Thaga — Fashion Brand on Instagram ",
    slug: "Suii_Thaga-Fashion-Brand-on-Instagram",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758869895/blog-app/categories/pefwucmj8d2hlpwjpjkb.jpg",
    subImage: "/assist/portfolio/marketing/Suii_thaga.png",
    description:
      "Suii_Thaga is a trendy Instagram brand that sources modern fashions to the current style conscious youth in the US. As a way to present the latest trends in the form of artistic reels, the page intends to turn quality content into a stronger performance and audience engagement, taking advantage of a specific Instagram strategy to establish meaningful connections and achieve the desired growth.",
    points: [
      "Course Landing Pages: Optimized for higher conversions.",
      "Knowledge Hub: Built extensive learning resources.",
      "Video Content: Produced engaging YouTube lessons.",
    ],
    date: "April – May 2025",
    duration: "1 Month",
    tools: [
      "   Instagram Analytics ",
      "Meta Ads Manager ",
      "Canva / Figma (Design Templates) ",
    ],
    client: "Suii_Thaga — Fashion Brand on Instagram ",
    location: "United States (Instagram-first brand)",
    modules: [
      " Content Calendar Planning ",
      "Reels & Story Optimization ",
      "Community Engagement ",
      "Instagram Ads Boosting ",
      "Hashtag & Caption Strategy ",
    ],
    expertise: [
      "   Instagram Growth Strategy ",
      "Content Marketing ",
      "Visual Identity Design ",
      "Performance Tracking ",
    ],
  },
  {
    id: 8,
    title: "ExamStudyZone.com — Educational Platform ",
    slug: "ExamStudyZone.com-Educational-Platform",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758792090/blog-app/categories/q7wzuvnmax3cuifsjghd.jpg",
    subImage: "/assist/portfolio/marketing/examStudy.png",
    description:
      "ExamStudyZone.com is a learning resource that provides study content for the examination of SAP-related courses, such as question banks, practice exams and PDFs. It also includes significant modules such as S/4HANA, MM, SD and ABAP, so students can have an easy and organized way of learning SAP outside of a classroom setting, providing clarity and proper preparation.",
    points: [
      "Neighborhood Guides: Content covering local living insights.",
      "SEO Listings: Optimized property pages for visibility.",
      "Lead Magnets: Created downloadable buyer’s guides.",
    ],
    date: "November 2024 – June 2025 ",
    duration: "8 Months ",
    tools: [
      "   Google Search Console ",
      "Bing Webmaster Tools ",
      "SEMrush ",
      "Ubersuggest ",
    ],
    client: "ExamStudyZone.com — Educational Platform",
    location: "Global (Online/E-learning Platform) ",
    modules: [
      "    SEO Optimization ",
      "Content Expansion ",
      "Technical Improvements ",
      "Monitoring & Analysis ",
    ],
    expertise: [
      "   Search Engine Optimization (SEO) ",
      "Content Strategy & Writing ",
      "Technical SEO & Site Optimization ",
      "Education Marketing ",
      "Keyword Research & Analytics ",
    ],
  },
  {
    id: 9,
    title: "iClinix — Specialized Eye Care Hospital ",
    slug: "iClinix-Specialized-Eye-Care-Hospital",
    image: "https://res.cloudinary.com/dpmceu66e/image/upload/v1758791774/blog-app/categories/ipmu4tyvldru9vssclbg.jpg",
    subImage: "/assist/portfolio/marketing/IClini.png",
    description:
      "iClinix is an eye care hospital that is a specialized facility with an intention of increasing patient calls and internet presence within a competitive digital environment. A combination of focused Google Ads to get instant leads and SEO to grow the business long-term helped the hospital to achieve more patient bookings and support brand credibility and establish the ground for organic traffic sustainability.",
    points: [
      "Financial Blogs: Created beginner-friendly investment articles.",
      "SEO Tools: Developed calculators & comparison pages.",
      "Email Campaigns: Sent targeted newsletters for leads.",
    ],
    date: "May 2025",
    duration: "1 Month ",
    tools: [
      "    Google Ads ",
      "Google Search Console ",
      "SEMrush ",
      "Local SEO Listings",
    ],
    client: "iClinix — Specialized Eye Care Hospital",
    location: "Delhi NCR, India ",
    modules: [
      " Google Ads Campaigns ",
      "SEO Optimization ",
      "Lead Generation ",
      "Content Strategy",
    ],
    expertise: [
      "  Search Engine Optimization (SEO) ",
      "Google Ads & PPC Campaigns ",
      "Local SEO & Patient Targeting ",
      "Healthcare Marketing ",
      "Content Optimization ",
    ],
  },
];

export default marketingProjects;
